export const SET_CITYIDS = 'SET_CITYIDS'

export const SET_OPENID = 'SET_OPENID'

export const SET_SHIPPING = 'SET_SHIPPING'

export const SET_RECEIVER = 'SET_RECEIVER'

export const SET_WXCODE = 'SET_WXCODE'

export const SET_STEP1DATA = 'SET_STEP1DATA'

export const SET_STEP2DATA = 'SET_STEP2DATA'

export const SET_CUSTOMERINFO = 'SET_CUSTOMERINFO'

export const SET_CUSTOMERORDERS = 'SET_CUSTOMERORDERS'

export const SET_DRIVERORDERS = 'SET_DRIVERORDERS'

export const SET_SHIPPINGDISTRICTDETAIL = 'SET_SHIPPINGDISTRICTDETAIL'

export const SET_RECEIVEDISTRICTDETAIL = 'SET_RECEIVEDISTRICTDETAIL'

export const SET_DRIVERMOBILEPHONE = 'SET_DRIVERMOBILEPHONE'

